### ISSUE TITLE
[FIX] Network Layer 모듈 수정

### ISSUE THREAD

**Issue by Do-hyun-Kim** [hobbyloop/hobbyloop-iOS#10]
## 📝 TO-DO
- [x] Network Layer 네이밍 수정 및 Entity 분리
- [x] Solid 원칙을 기반으로 구현
- [x] 사용하지 않는 Code 제거 및 프로젝트 폴더 정리

## 🧑‍💻 Description
- Network Layer 중복되는 네이밍 수정, Entity는 HPDomain으로 분리 작업
- DIP, DI을 사용하여 구현
- 중복되는 Method 및 불필요한 Code 제거
