### ISSUE TITLE
[FEAT] Social Login API 연동 및 UI 개선 작업

### ISSUE THREAD

**Issue by Do-hyun-Kim** [hobbyloop/hobbyloop-iOS#12]
## 📝 TO-DO
- [x] Google Login, Apple Login API 연동 작업
- [x] ScrollView UI 개선 작업 및 , Height 값 수정
- [x] SignUpView Figma UI 수정 및 약관동의 화면 구현

## 🧑‍💻 Description
- Google Login, Apple Login API 작업 추가 및 Access Token 값 가져오도록 기능 구현 
- ScrollView Keyboard 숨겨지는 기능 및 Height 값 동적으로 수정
