### ISSUE TITLE
[FEAT] HomeController 구현 및 CustomNavigationController 작업

### ISSUE THREAD

**Issue by Do-hyun-Kim** [hobbyloop/hobbyloop-iOS#18]
## 📝 TO-DO
- [x] HomeController UI 작업 및 business logic 구현
- [x] `Tuist` CommonUI CustomNavigationController 구현
- [x] OnboardingController UI 구현
- [x] Calendar View 모듈화 작업

## 🧑‍💻 Description
- CustomNavigationController 구현을 통해 화면 단에 따라 NavigationBarItem 배치 설정
- HomeController UI 구현
- OnboardingController UI 구현
- Figma Design 바탕으로 CalendarView 모듈화 작업
