### ISSUE TITLE
[FEAT] 수업 에약 및 수업 예약 시간 선택 UI 구현

### ISSUE THREAD

**Issue by Do-hyun-Kim** [hobbyloop/hobbyloop-iOS#31]
## 📝 TO-DO
- [x] 수업 예약 UI 및 예약 시간 선택 UI 구현
- [x] UIView Extensions Custom TicketView 구현
- [x] HPCalendar Weekly View UI 활용하여 UI 구현

## 🧑‍💻 Description
- 수업 예약 페이지는 Swift 내부 프레임 워크에서 제공되는 `insetGrouped` Style 활용하여 `tableView` 구현
- `UIView` Extensions 내부에 function을 활용하여 Custom TicketView 구현
- `HPCalendarWeeklyView` Custom UI 활용하여 UI 구현
