### ISSUE TITLE
[FEAT] Login AuthenticationCredential 기능 추가

### ISSUE THREAD

**Issue by Do-hyun-Kim** [hobbyloop/hobbyloop-iOS#37]
## 📝 TO-DO
- [x] `ServerNetworking` Log Event 상세히 디버깅 하기위해 `EventMonitor` 구현
- [x] `EventMonter`, `AuthenticationCredential` Session에 넣어주기 위한 Protocol 구현 
- [x] `KeyChainAcess` Third Party Library 의존성 추가

## 🧑‍💻 Description
- AccessToken, Login 체크 여부를 `Singleton pattern`을 활용하여 필요한 화면단에서 사용할 수 있도록 구현, 및 RootViewController 변경
- EventMonitor를 통해 `Header` Value 와 `Response Data`, Status Code에 상세 정보 디버깅
- AuthenticationCredential를 통해 `401` Error시 AccessToken 재발급 로직 추가
- `KeyChainAcess` 라이브러리 추가 밎 `extensions`  활용하여 key 값을 `KeyChainsKeys` 값으로 Setting 하도록 변경
